azure:
  tenant: 1ca4042a-6212-45c4-89d2-46f903825df5
  subscription_id: 59eb0c35-11ec-477d-852a-6d58ed776b49
  resource_group: sgjml
  principal_name: azureprincipal
  credentials_file: .principal.json
  
azureml:
  azure_region: westeurope

azureml_job:
  compute_instance_size: STANDARD_D2S_V3
  compute_max_instances: 2
  name: model_training_hyper
  training_folder: files
  training_script: main.py

azureml_endpoint_autoscale_settings:
  metric: CpuUtilizationPercentage
  initial_capacity: 1
  compute_instance_size: Standard_D2as_v4
  scale_out_threashold: 70
  scale_in_threashold: 30