azure:
  tenant: PUT_YOUR_TENANT_ID
  subscription_id: PUT_YOUR_SUBSCRIPTION_ID
  resource_group: PUT_YOUR_RG_NAME_AND_RESOURCE_NAME_PREFIX
  principal_name: azureprincipal
  credentials_file: .principal.json
  
azureml:
  azure_region: PUT_YOUR_AZURE_REGION_OF_CHOICE

azureml_job:
  compute_instance_size: STANDARD_D2S_V3
  compute_max_instances: 2
  name: model_training_hyper
  training_folder: files
  training_script: main.py

azureml_endpoint_autoscale_settings:
  metric: CpuUtilizationPercentage
  initial_capacity: 1
  compute_instance_size: Standard_D2as_v4
  scale_out_threashold: 70
  scale_in_threashold: 30